### ISSUE TITLE
flink-connector-starrocks--only support OlapTable currently, but Table [] is not a OlapTable，目前不支持视图表么？

### ISSUE THREAD

**Issue by hangupwd** [StarRocks/starrocks-connector-for-apache-flink#178]
```
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Request of get query plan failed with code 403 {"exception":"only support OlapTable currently, but Table [collective_42351] is not a OlapTable","status":403}
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-clients_2.11-1.14.2.jar:1.14.2]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-clients_2.11-1.14.2.jar:1.14.2]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-clients_2.11-1.14.2.jar:1.14.2]
	at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:84) ~[flink-clients_2.11-1.14.2.jar:1.14.2]
	at org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:70) ~[flink-clients_2.11-1.14.2.jar:1.14.2]
	at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$0(JarRunHandler.java:104) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.RuntimeException: Request of get query plan failed with code 403 {"exception":"only support OlapTable currently, but Table [collective_42351] is not a OlapTable","status":403}
	at com.xasj.flink.starrocksflink.manager.StarRocksQueryPlanVisitor.getQueryPlan(StarRocksQueryPlanVisitor.java:126) ~[?:?]
	at com.xasj.flink.starrocksflink.manager.StarRocksQueryPlanVisitor.getQueryInfo(StarRocksQueryPlanVisitor.java:56) ~[?:?]
	at com.xasj.flink.starrocksflink.table.source.StarRocksSourceCommonFunc.getQueryInfo(StarRocksSourceCommonFunc.java:200) ~[?:?]
	at com.xasj.flink.starrocksflink.table.source.StarRocksDynamicSourceFunction.<init>(StarRocksDynamicSourceFunction.java:66) ~[?:?]
	at com.xasj.flink.starrocksflink.StarRocksSource.source(StarRocksSource.java:33) ~[?:?]
	at com.xasj.business.ontology.OntologyVertexBusiness.main(OntologyVertexBusiness.java:74) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-clients_2.11-1.14.2.jar:1.14.2]
	... 7 more
```
sr-v2.2.0
flink-connector-starrocks-1.2.5_flink-1.15
当前flink-connector-starrocks读取数据不支持视图么

**Comment by banmoy** [comment]
是的，目前不支持视图

**Comment by ltylty** [comment]
> 

在文档里写一下吧。  一看文档啥都可以，一用起来都是限制。
