### ISSUE TITLE
不支持二进制数据（binary、bytes）的读取和写入

### ISSUE THREAD

**Issue by liuka11** [StarRocks/starrocks-connector-for-apache-flink#362]
java.lang.UnsupportedOperationException: Unsupported type:BYTES
	at com.starrocks.connector.flink.row.sink.StarRocksTableRowTransformer.typeConvertion(StarRocksTableRowTransformer.java:183)
	at com.starrocks.connector.flink.row.sink.StarRocksTableRowTransformer.transform(StarRocksTableRowTransformer.java:96)
	at com.starrocks.connector.flink.row.sink.StarRocksTableRowTransformer.transform(StarRocksTableRowTransformer.java:50)
	at com.starrocks.connector.flink.table.sink.StarRocksDynamicSinkFunctionV2.invoke(StarRocksDynamicSinkFunctionV2.java:164)

**Comment by nishant1151** [comment]
Possible Causes:

StarRocks incompatibility: The version of StarRocks you're using might not natively support the "BYTES" data type. Check StarRocks documentation for supported data types.
Connector limitation: The StarRocks connector for Flink might not have implemented the logic to handle "BYTES" data yet. Refer to the connector's documentation or release notes.
Troubleshooting Steps:

Check StarRocks documentation: Verify if StarRocks supports the "BYTES" data type. If not, you'll need to convert the data to a supported type before sending it to StarRocks.
Review Flink connector documentation: See if the StarRocks connector for Flink has documented support for "BYTES" data. If not, you might need to wait for an update or find a workaround.
Search online resources: Look for solutions or discussions related to "java.lang.UnsupportedOperationException: Unsupported type: BYTES" in the context of StarRocks and Flink. You might find solutions from other users who faced similar issues.
Potential Workarounds (depending on the cause):

Data conversion: If StarRocks supports a different data type that can represent your data, convert the "BYTES" data to that type before sending it to StarRocks. You might need to write custom logic for this conversion.
Upgrade connector: If a newer version of the StarRocks connector for Flink has support for "BYTES" data, consider upgrading.
